[versions]
minSdk = "23"
targetSdk = "35"
cronetApi = "119.6045.31"
cronetOkhttp = "0.1.0"
playServicesCronet = "18.1.0"
androidx-appcompat = "1.7.0"
androidx-compose-ui = "1.7.5"
androidx-material3 = "1.3.1"
material = "1.12.0"
androidx-activity = "1.9.3"
androidx-core = "1.15.0"
androidx-lifecycle = "2.8.7"
okhttp = "4.12.0"
zoomable = "0.11.2"
compose-bom = "2024.11.00"

#plugins
android-gradle-plugin = "8.7.3"
kotlin = "2.0.10"
gradleCacheFix = "3.0.1"
dokka = "1.9.20"
vanniktech-maven-publish = "0.29.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-material3" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
cronet-api = { module = "org.chromium.net:cronet-api", version.ref = "cronetApi" }
cronet-okhttp = { module = "com.google.net.cronet:cronet-okhttp", version.ref = "cronetOkhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-cronet = { module = "com.google.android.gms:play-services-cronet", version.ref = "playServicesCronet" }
zoomable = { module = "me.saket.telephoto:zoomable", version.ref = "zoomable" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
gradle-cachefix = { id = "org.gradle.android.cache-fix", version.ref = "gradleCacheFix" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
